version: '3.9'
services:
  backend:
    container_name: app_backend
    build: .
    volumes:
      - .:/usr/app_backend
    restart: 'always'
    ports:
      - 8819:8819
    platform: linux/x86_64
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mongo:latest
    container_name: mongo_db
    platform: linux/arm64/v8
    ports:
      - 27017:27017
    env_file:
      - .env
    restart: 'always'